name: API Tests
on:
  push:
    branches: [ main, develop ]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Run tests
        working-directory: tests
        env:
          BASE_URL: ${{ secrets.BASE_URL || 'http://localhost:59546' }}
          API_KEY:  ${{ secrets.API_KEY || '' }}
        run: mvn -q -DskipTests=false test
